-- ============================================================================
-- cilek_dozlama - PostgreSQL şeması (Sis/Fog katmanı: yerel sunucu, sistem kaydı)
-- Çalıştırma:  psql -U postgres -f schema.sql
-- TimescaleDB (opsiyonel zaman-serisi optimizasyonu) için dosyanın sonuna bakınız.
-- ============================================================================

DROP DATABASE IF EXISTS cilek_dozlama;
CREATE DATABASE cilek_dozlama WITH ENCODING 'UTF8' TEMPLATE template0;
\connect cilek_dozlama

-- ---- ENUM etki alanları --------------------------------------------------
CREATE TYPE durum_t        AS ENUM ('AKTIF','PASIF');
CREATE TYPE cozelti_turu_t AS ENUM ('ASIT','BAZ','BESIN_A','BESIN_B','SU');
CREATE TYPE cihaz_turu_t   AS ENUM ('POMPA','VALF','SENSOR');
CREATE TYPE tetik_turu_t   AS ENUM ('OTOMATIK','MANUEL');
CREATE TYPE parti_durum_t  AS ENUM ('AKTIF','HASAT_EDILDI','IPTAL');
CREATE TYPE alarm_durum_t  AS ENUM ('AKTIF','COZULDU');

-- ---- Ortak: guncellenme + surum (iyimser kilitleme) tetikleyicisi --------
CREATE OR REPLACE FUNCTION trg_set_guncellenme() RETURNS trigger AS $$
BEGIN
  NEW.guncellenme := now();
  NEW.surum := OLD.surum + 1;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================ ANA TABLOLAR =================================

-- 1) kullanici
CREATE TABLE kullanici (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kullanici_adi   VARCHAR(50)  NOT NULL UNIQUE,
  parola_hash     CHAR(64)     NOT NULL,
  ad_soyad        VARCHAR(100) NOT NULL,
  yetki_seviyesi  SMALLINT     NOT NULL DEFAULT 0,
  olusturulma     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  guncellenme     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  surum           INTEGER      NOT NULL DEFAULT 1,
  CONSTRAINT chk_kullanici_yetki CHECK (yetki_seviyesi IN (0,1)),
  CONSTRAINT chk_kullanici_ad    CHECK (char_length(kullanici_adi) >= 3)
);
CREATE TRIGGER trg_kullanici_upd BEFORE UPDATE ON kullanici
  FOR EACH ROW EXECUTE FUNCTION trg_set_guncellenme();

-- 2) sera
CREATE TABLE sera (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sera_kodu    VARCHAR(30)  NOT NULL UNIQUE,
  sera_ad      VARCHAR(100) NOT NULL,
  konum        VARCHAR(150),
  olusturulma  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  guncellenme  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  surum        INTEGER      NOT NULL DEFAULT 1
);
CREATE TRIGGER trg_sera_upd BEFORE UPDATE ON sera
  FOR EACH ROW EXECUTE FUNCTION trg_set_guncellenme();

-- 3) recete
CREATE TABLE recete (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recete_kodu  VARCHAR(30)  NOT NULL UNIQUE,
  recete_ad    VARCHAR(100) NOT NULL,
  cesit        VARCHAR(60),
  aciklama     TEXT,
  olusturulma  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  guncellenme  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  surum        INTEGER      NOT NULL DEFAULT 1
);
CREATE TRIGGER trg_recete_upd BEFORE UPDATE ON recete
  FOR EACH ROW EXECUTE FUNCTION trg_set_guncellenme();

-- 4) buyume_evresi
CREATE TABLE buyume_evresi (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evre_kodu     VARCHAR(30)  NOT NULL UNIQUE,
  recete_id     BIGINT       NOT NULL,
  sira_no       SMALLINT     NOT NULL,
  evre_ad       VARCHAR(80)  NOT NULL,
  hedef_ph_min  NUMERIC(4,2) NOT NULL,
  hedef_ph_max  NUMERIC(4,2) NOT NULL,
  hedef_ec_min  NUMERIC(5,2) NOT NULL,
  hedef_ec_max  NUMERIC(5,2) NOT NULL,
  CONSTRAINT fk_evre_recete FOREIGN KEY (recete_id) REFERENCES recete(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT uq_evre_recete_sira UNIQUE (recete_id, sira_no),
  CONSTRAINT chk_evre_ph CHECK (hedef_ph_min >= 0 AND hedef_ph_max <= 14 AND hedef_ph_min < hedef_ph_max),
  CONSTRAINT chk_evre_ec CHECK (hedef_ec_min >= 0 AND hedef_ec_min < hedef_ec_max)
);

-- 5) parti
CREATE TABLE parti (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parti_kodu     VARCHAR(30)   NOT NULL UNIQUE,
  recete_id      BIGINT        NOT NULL,
  sera_id        BIGINT        NOT NULL,
  aktif_evre_id  BIGINT,
  ekim_tarihi    DATE          NOT NULL,
  hasat_tarihi   DATE,
  durum          parti_durum_t NOT NULL DEFAULT 'AKTIF',
  olusturulma    TIMESTAMPTZ   NOT NULL DEFAULT now(),
  guncellenme    TIMESTAMPTZ   NOT NULL DEFAULT now(),
  surum          INTEGER       NOT NULL DEFAULT 1,
  CONSTRAINT fk_parti_recete FOREIGN KEY (recete_id) REFERENCES recete(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_parti_sera FOREIGN KEY (sera_id) REFERENCES sera(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_parti_evre FOREIGN KEY (aktif_evre_id) REFERENCES buyume_evresi(id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_parti_hasat CHECK (hasat_tarihi IS NULL OR hasat_tarihi >= ekim_tarihi)
);
CREATE TRIGGER trg_parti_upd BEFORE UPDATE ON parti
  FOR EACH ROW EXECUTE FUNCTION trg_set_guncellenme();

-- 6) tank
CREATE TABLE tank (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tank_kodu       VARCHAR(30)    NOT NULL UNIQUE,
  sera_id         BIGINT         NOT NULL,
  cozelti_turu    cozelti_turu_t NOT NULL,
  kapasite_litre  NUMERIC(7,2)   NOT NULL,
  mevcut_litre    NUMERIC(7,2)   NOT NULL DEFAULT 0,
  olusturulma     TIMESTAMPTZ    NOT NULL DEFAULT now(),
  guncellenme     TIMESTAMPTZ    NOT NULL DEFAULT now(),
  surum           INTEGER        NOT NULL DEFAULT 1,
  CONSTRAINT fk_tank_sera FOREIGN KEY (sera_id) REFERENCES sera(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT uq_tank_sera_tur UNIQUE (sera_id, cozelti_turu),
  CONSTRAINT chk_tank_kap    CHECK (kapasite_litre > 0),
  CONSTRAINT chk_tank_mevcut CHECK (mevcut_litre >= 0 AND mevcut_litre <= kapasite_litre)
);
CREATE TRIGGER trg_tank_upd BEFORE UPDATE ON tank
  FOR EACH ROW EXECUTE FUNCTION trg_set_guncellenme();

-- 7) cihaz
CREATE TABLE cihaz (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cihaz_kodu   VARCHAR(30)  NOT NULL UNIQUE,
  sera_id      BIGINT       NOT NULL,
  tank_id      BIGINT,
  cihaz_turu   cihaz_turu_t NOT NULL,
  durum        durum_t      NOT NULL DEFAULT 'AKTIF',
  olusturulma  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  guncellenme  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  surum        INTEGER      NOT NULL DEFAULT 1,
  CONSTRAINT fk_cihaz_sera FOREIGN KEY (sera_id) REFERENCES sera(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_cihaz_tank FOREIGN KEY (tank_id) REFERENCES tank(id)
    ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE TRIGGER trg_cihaz_upd BEFORE UPDATE ON cihaz
  FOR EACH ROW EXECUTE FUNCTION trg_set_guncellenme();

-- ===================== ZAMAN SERİSİ / OLAY TABLOLARI ======================

-- 8) sensor_okuma (yüksek hacimli zaman serisi)
CREATE TABLE sensor_okuma (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sera_id       BIGINT      NOT NULL,
  olcum_zamani  TIMESTAMPTZ NOT NULL DEFAULT now(),
  ph            NUMERIC(4,2),
  ec            NUMERIC(5,2),
  sicaklik      NUMERIC(4,1),
  su_seviyesi   NUMERIC(5,2),
  kalite_bayragi SMALLINT  NOT NULL DEFAULT 1,   -- 1=normal, 2=supheli, 3=karantina (yardimci YZ/TinyML)
  kaynak         VARCHAR(12) NOT NULL DEFAULT 'olay',  -- 'olay' (ham, olay tabanli) | 'ozet' (pencere ozetinden) | 'elle'
  kaynak        VARCHAR(40),                      -- veri kaynagi / hub kimligi (idempotentlik/izlenebilirlik)
  CONSTRAINT fk_okuma_sera FOREIGN KEY (sera_id) REFERENCES sera(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT chk_okuma_ph CHECK (ph IS NULL OR (ph >= 0 AND ph <= 14)),
  CONSTRAINT chk_okuma_ec CHECK (ec IS NULL OR ec >= 0),
  CONSTRAINT chk_okuma_su CHECK (su_seviyesi IS NULL OR (su_seviyesi >= 0 AND su_seviyesi <= 100)),
  CONSTRAINT chk_okuma_kalite CHECK (kalite_bayragi IN (1,2,3)),
  CONSTRAINT chk_okuma_kaynak CHECK (kaynak IN ('olay','ozet','elle'))
);
CREATE INDEX idx_okuma_sera_zaman ON sensor_okuma (sera_id, olcum_zamani DESC);
-- Ekleme-ağırlıklı zaman sütunu için alan-verimli BRIN indeksi
CREATE INDEX idx_okuma_zaman_brin ON sensor_okuma USING BRIN (olcum_zamani);

-- 9) sensor_ozet (pencere özetleri / downsampling)
CREATE TABLE sensor_ozet (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sera_id       BIGINT      NOT NULL,
  pencere_basi  TIMESTAMPTZ NOT NULL,
  ornek_sayisi  INTEGER     NOT NULL,
  ph_ort NUMERIC(4,2), ph_min NUMERIC(4,2), ph_max NUMERIC(4,2),
  ec_ort NUMERIC(5,2), ec_min NUMERIC(5,2), ec_max NUMERIC(5,2),
  CONSTRAINT fk_ozet_sera FOREIGN KEY (sera_id) REFERENCES sera(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT uq_ozet_sera_pencere UNIQUE (sera_id, pencere_basi),
  CONSTRAINT chk_ozet_ornek CHECK (ornek_sayisi > 0)
);
CREATE INDEX idx_ozet_sera_zaman ON sensor_ozet (sera_id, pencere_basi DESC);

-- 10) dozlama_kaydi
CREATE TABLE dozlama_kaydi (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sera_id         BIGINT       NOT NULL,
  tank_id         BIGINT       NOT NULL,
  cihaz_id        BIGINT,
  parti_id        BIGINT,
  dozlama_zamani  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  miktar_ml       NUMERIC(7,2) NOT NULL,
  oncesi          NUMERIC(5,2),
  sonrasi         NUMERIC(5,2),
  degisim         NUMERIC(6,2) GENERATED ALWAYS AS (sonrasi - oncesi) STORED,
  tetik_turu      tetik_turu_t NOT NULL DEFAULT 'OTOMATIK',
  CONSTRAINT fk_doz_sera  FOREIGN KEY (sera_id)  REFERENCES sera(id)  ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_doz_tank  FOREIGN KEY (tank_id)  REFERENCES tank(id)  ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_doz_cihaz FOREIGN KEY (cihaz_id) REFERENCES cihaz(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_doz_parti FOREIGN KEY (parti_id) REFERENCES parti(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_doz_miktar CHECK (miktar_ml > 0)
);
CREATE INDEX idx_doz_sera_zaman ON dozlama_kaydi (sera_id, dozlama_zamani DESC);

-- 11) alarm
CREATE TABLE alarm (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sera_id         BIGINT        NOT NULL,
  alarm_turu      VARCHAR(40)   NOT NULL,
  mesaj           VARCHAR(200),
  deger           NUMERIC(8,2),                -- alarmi tetikleyen olcum degeri (orn. pH/EC/su)
  olusma_zamani   TIMESTAMPTZ   NOT NULL DEFAULT now(),
  cozulme_zamani  TIMESTAMPTZ,
  durum           alarm_durum_t NOT NULL DEFAULT 'AKTIF',
  CONSTRAINT fk_alarm_sera FOREIGN KEY (sera_id) REFERENCES sera(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT chk_alarm_cozulme CHECK (cozulme_zamani IS NULL OR cozulme_zamani >= olusma_zamani)
);
CREATE INDEX idx_alarm_sera_durum ON alarm (sera_id, durum);

-- ---- Tetikleyici: alarm kapanış zamanı -----------------------------------
CREATE OR REPLACE FUNCTION trg_alarm_kapanis() RETURNS trigger AS $$
BEGIN
  IF NEW.durum = 'COZULDU' AND OLD.durum <> 'COZULDU' AND NEW.cozulme_zamani IS NULL THEN
    NEW.cozulme_zamani := now();
  ELSIF NEW.durum = 'AKTIF' THEN
    NEW.cozulme_zamani := NULL;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_alarm_kapanis_b BEFORE UPDATE ON alarm
  FOR EACH ROW EXECUTE FUNCTION trg_alarm_kapanis();

-- ---- Tetikleyici: dozlama sonrası tank stok düşümü -----------------------
CREATE OR REPLACE FUNCTION trg_dozlama_stok() RETURNS trigger AS $$
BEGIN
  UPDATE tank
     SET mevcut_litre = GREATEST(0, mevcut_litre - NEW.miktar_ml / 1000.0)
   WHERE id = NEW.tank_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_dozlama_stok_a AFTER INSERT ON dozlama_kaydi
  FOR EACH ROW EXECUTE FUNCTION trg_dozlama_stok();

-- ============================= GÖRÜNÜMLER =================================
CREATE VIEW v_son_okuma AS
  SELECT sera_id, olcum_zamani, ph, ec, sicaklik, su_seviyesi
    FROM (
      SELECT s.*, ROW_NUMBER() OVER (
               PARTITION BY sera_id ORDER BY olcum_zamani DESC, id DESC) AS sira
        FROM sensor_okuma s
    ) t WHERE sira = 1;

CREATE VIEW v_aktif_alarm AS
  SELECT * FROM alarm WHERE durum = 'AKTIF';

CREATE VIEW v_gunluk_dozlama AS
  SELECT d.sera_id, t.cozelti_turu, d.dozlama_zamani::date AS gun,
         COUNT(*) AS dozlama_sayisi, SUM(d.miktar_ml) AS toplam_ml
    FROM dozlama_kaydi d
    JOIN tank t ON t.id = d.tank_id
   GROUP BY d.sera_id, t.cozelti_turu, d.dozlama_zamani::date;

-- ============================================================================
-- OPSİYONEL: TimescaleDB ile zaman-serisi optimizasyonu (ölçek/yazma/sıkıştırma)
-- ----------------------------------------------------------------------------
-- CREATE EXTENSION IF NOT EXISTS timescaledb;
-- -- sensor_okuma'yı hypertable'a çevir (otomatik zaman bölümleme):
-- SELECT create_hypertable('sensor_okuma', 'olcum_zamani', migrate_data => true);
-- -- Sürekli toplama (continuous aggregate): sensor_ozet'in otomatik üretimi
-- CREATE MATERIALIZED VIEW sensor_ozet_5dk WITH (timescaledb.continuous) AS
--   SELECT sera_id, time_bucket('5 minutes', olcum_zamani) AS pencere_basi,
--          count(*) AS ornek_sayisi,
--          avg(ph) AS ph_ort, min(ph) AS ph_min, max(ph) AS ph_max,
--          avg(ec) AS ec_ort, min(ec) AS ec_min, max(ec) AS ec_max
--     FROM sensor_okuma GROUP BY sera_id, time_bucket('5 minutes', olcum_zamani);
-- -- Sütun bazlı sıkıştırma ve retention politikaları:
-- ALTER TABLE sensor_okuma SET (timescaledb.compress, timescaledb.compress_segmentby = 'sera_id');
-- SELECT add_compression_policy('sensor_okuma', INTERVAL '7 days');
-- SELECT add_retention_policy   ('sensor_okuma', INTERVAL '180 days');
-- ============================================================================

-- ============================================================================
--  YARDIMCI YAPAY ZEKA / VERİ KALİTESİ / SOY-KÜTÜĞÜ TABLOLARI  (bölüm 7.3.19)
--  Bu tablolar otonom dozlamayı DEĞİŞTİRMEZ; veri temizleme, anomali/sensör
--  arıza işaretleme, model kayıt/karar loglama ve çevrimdışı RL içindir.
-- ============================================================================

-- Sensör kalibrasyon geçmişi (ofset/eğim düzeltmeleri)
CREATE TABLE kalibrasyon (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cihaz_id           BIGINT      NOT NULL,
  parametre          VARCHAR(20) NOT NULL,            -- 'pH','EC','sicaklik'
  ofset              NUMERIC(8,4) NOT NULL DEFAULT 0,
  egim               NUMERIC(8,4) NOT NULL DEFAULT 1,
  kalibrasyon_zamani TIMESTAMPTZ NOT NULL DEFAULT now(),
  aciklama           TEXT,
  CONSTRAINT fk_kalib_cihaz FOREIGN KEY (cihaz_id) REFERENCES cihaz(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

-- Sensör/aktüatör arıza ve işaret kayıtları (kestirimci bakım)
CREATE TABLE sensor_ariza (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cihaz_id    BIGINT      NOT NULL,
  ariza_turu  VARCHAR(40) NOT NULL,                  -- 'kayma','takili_deger','aralik_disi','iletisim'
  baslangic   TIMESTAMPTZ NOT NULL DEFAULT now(),
  bitis       TIMESTAMPTZ,
  detay       TEXT,
  CONSTRAINT fk_ariza_cihaz FOREIGN KEY (cihaz_id) REFERENCES cihaz(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

-- Model kayıt defteri (sürüm + başarım metrikleri + konum)
CREATE TABLE model_kayit (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ad               VARCHAR(80) NOT NULL,             -- 'hub_tinyml_anomali','sunucu_ph_tahmin'...
  surum            VARCHAR(40) NOT NULL,
  konum            VARCHAR(20) NOT NULL DEFAULT 'sunucu',  -- 'hub'|'sunucu'|'bulut'
  metrik_json      JSONB,
  egitim_baslangic TIMESTAMPTZ,
  egitim_bitis     TIMESTAMPTZ,
  olusturma_zamani TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_model UNIQUE (ad, surum),
  CONSTRAINT chk_model_konum CHECK (konum IN ('hub','sunucu','bulut'))
);

-- Tahmin logu (tahmin vs gerçek -> drift izleme)
CREATE TABLE tahmin_log (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id      BIGINT      NOT NULL,
  sera_id       BIGINT,
  tahmin_zamani TIMESTAMPTZ NOT NULL DEFAULT now(),
  parametre     VARCHAR(20),
  tahmin        NUMERIC(10,4),
  gercek        NUMERIC(10,4),
  CONSTRAINT fk_tahmin_model FOREIGN KEY (model_id) REFERENCES model_kayit(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_tahmin_sera FOREIGN KEY (sera_id) REFERENCES sera(id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

-- Karar logu (gölge mod önerileri; aktüatöre uygulanıp uygulanmadığı)
CREATE TABLE karar_log (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id     BIGINT,
  sera_id      BIGINT,
  karar_zamani TIMESTAMPTZ NOT NULL DEFAULT now(),
  oneri        TEXT,
  uygulandi    BOOLEAN     NOT NULL DEFAULT false,
  CONSTRAINT fk_karar_model FOREIGN KEY (model_id) REFERENCES model_kayit(id)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_karar_sera FOREIGN KEY (sera_id) REFERENCES sera(id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

-- Çevrimdışı RL geçişleri: (durum, eylem, ödül, sonraki durum)
CREATE TABLE gecis (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sera_id            BIGINT,
  zaman              TIMESTAMPTZ NOT NULL DEFAULT now(),
  durum_json         JSONB       NOT NULL,
  eylem_json         JSONB       NOT NULL,
  odul               NUMERIC(12,5),
  sonraki_durum_json JSONB,
  CONSTRAINT fk_gecis_sera FOREIGN KEY (sera_id) REFERENCES sera(id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX idx_okuma_kalite ON sensor_okuma (kalite_bayragi, olcum_zamani DESC);
CREATE INDEX idx_tahmin_model ON tahmin_log (model_id, tahmin_zamani DESC);
